version: "3.8"

services:

  # ─── MySQL untuk Ticket Service ───────────────────────────
  db_ticket:
    image: postgres:15
    container_name: db_ticket
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: db_ticket
    volumes:
      - db_ticket_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"           # port 5433 di host agar tidak bentrok
    networks:
      - tubes_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ─── Ticket Service (Laravel) ─────────────────────────────
  ticket-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ticket-service
    restart: unless-stopped
    ports:
      - "8004:8000"
    env_file:
      - .env
    environment:
      DB_HOST: db_ticket
      REDIS_HOST: redis-local
      USER_SERVICE_URL: http://user-service:8002
      EVENT_SERVICE_URL: http://event_service:8000
      PAYMENT_SERVICE_URL: http://payment-service:8000
    depends_on:
      db_ticket:
        condition: service_healthy
    networks:
      - tubes_network

  # ─── Hasura GraphQL Engine ────────────────────────────────
  # Terhubung ke db_ticket, generate GraphQL endpoint otomatis
  hasura:
    image: hasura/graphql-engine:v2.16.0
    container_name: hasura
    restart: unless-stopped
    ports:
      - "8085:8080"           # Hasura Console: http://localhost:8080
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:hasurasecret@postgres_hasura:5432/hasura_metadata
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: "myadminsecretkey"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "public"
    depends_on:
      db_ticket:
        condition: service_healthy
      postgres_hasura:
        condition: service_started 
    networks:
      - tubes_network

  postgres_hasura:
    image: postgres:15
    container_name: postgres_hasura
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: hasurasecret
      POSTGRES_DB: hasura_metadata
    networks:
      - tubes_network
      

volumes:
  db_ticket_data:

networks:
  tubes_network:
    external: true           # shared network dengan service lain
    name: tubes_network
